### PR TITLE
Update ppo_rllib_client.py

### PR DESCRIPTION
**Pull request by nabazar**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by nabazar** [comment]
Hi Dear,
The updated version will look something like this:

from ray.rllib.algorithms.ppo import PPO
instead of...

from ray.rllib.agents.ppo import PPO

**Comment by micahcarroll** [comment]
Why are you making this change? Is it because rllib has updated? If so, we won't default the newer version of rllib unless someone makes a PR which comprehensively fixes issues throughout the repo

**Comment by nabazar** [comment]
Hi
Thank you for your reply
I need your help to resolve the resulted issues and errors when I run your
code. I want to resolve the following issues:

1. I want to rewrite the code in colab.is it applicable?

2. When I run your code I face the following error:
import ray
from ray.rllib.agents.ppo import PPOTrainer
No module named 'ray.rllib.agents'

3. It seems I should use the non-updated version of the rlib library

Would you please help me with this?

Best regards
Nemat

**Comment by nabazar** [comment]
Thank you, sir,
I will do

**Pull request closed without merging**
