### PR TITLE
Base gym rendering implementation

### PR DESCRIPTION
**Pull request by wduguay-air**
# Description

Added a base gym rendering method. Render return format: RGB array. The visualization was tested with a third party RLHF framework called [Cogment-Verse](https://cogment.ai/cogment_verse) ([github](https://github.com/cogment/cogment-verse)). 

Cogment-Verse is currently setup to install a fork of this repository with the suggested change. See this [doc](https://github.com/cogment/cogment-verse/blob/main/docs/develop/overcooked_ai.md) for instructions.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by micahcarroll** [comment]
Thanks @wduguay-air! If you can get the final checks passing that would be great:
- The exact linting commands can be found in the [github actions script](https://github.com/HumanCompatibleAI/overcooked_ai/blob/master/.github/workflows/pythonlint.yml) and [here](https://github.com/HumanCompatibleAI/overcooked_ai/blob/master/.github/workflows/blackisort.yml).
- Probably the changes require adding `cv` to the requirements in `setup.py`

**Comment by wduguay-air** [comment]
Ran linters, updated `setup.py` for opencv-python.

**Comment by wduguay-air** [comment]
Could you approve the workflows?

**Comment by micahcarroll** [comment]
Yes, sorry I missed the previous message!

**Comment by wduguay-air** [comment]
I didn't have the right black version. Linters now fixed. Workflows should pass now.

**Comment by micahcarroll** [comment]
Thanks so much @wduguay-air!! Appreciate you making the PR and following up! Sorry for my slow response!

**Pull request merged**
